name: 'Mariachi'
description: 'Sends Pull Request review reminders to Microsoft Teams channels'
inputs:
  github_token:
    description: 'This is the default token set and created by GitHub. you can also use a personal access token with repo scope enabled, but this one is already available'
    required: false
    default: ${{ github.token }}
  teams_url: 
    description: "your Teams channel's webhook URL. here we assume it's in your repo's secrets store"
    required: true
  exclude_heads:
    description: 'Head Git branches to exclude'
    required: false
  exclude_labels:
    description: 'Labels to exclude'
    required: false
  min_reviews:
    description: 'Minimum number of reviews needed'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'bell'
  color: 'blue'
